config/routes.rb
Rails.application.routes.draw do
  root to: "tracks#index"
  match "/*artist/*track" => "tracks#show", via: [:get]
  match "/*playlist" => "tracks#playlist", via: [:get]
end

app/models/track.rb
class Track < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
    artist = params[:artist]
    track = params[:track]
    @url = "http://soundcloud.com/#{artist}/#{track}"
    @soundcloud_track = Soundcloud.client.get('/resolve', :url => @url)
  end

  def playlist
    playlist = params[:playlist]
    @url = "http://soundcloud.com/alexbaldwin/sets/#{playlist}"
    @playlist_url = @url
    @soundcloud_playlist = Soundcloud.client.get('/resolve', :url => @url)
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url, notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      # @track = Track.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params[:track]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
      <%= metamagic title: "Console.fm", description: "Top 100 electronic music charts" %>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <link href="//d2v52k3cl9vedd.cloudfront.net/basscss/6.0.2/basscss.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/progress.css" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js"></script>
    <script src="//d2v52k3cl9vedd.cloudfront.net/plangular/3.1.0/plangular.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular-hotkeys/1.4.5/hotkeys.min.js"></script>
    <script src="//use.typekit.net/aoa2ooy.js"></script>
    <script>try{Typekit.load();}catch(e){}</script>
  </head>
  <body ng-app="app">
    <%= yield %>
  </body>
  <script>
    var app = angular.module('app', ['plangular', 'cfp.hotkeys'])
    .config(function(plangularConfigProvider){
      plangularConfigProvider.clientId = '281bf78db858fb70bf8ccef48976dde4';
    });
  </script>
  <script>
    (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
    function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
    e=o.createElement(i);r=o.getElementsByTagName(i)[0];
    e.src='https://www.google-analytics.com/analytics.js';
    r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
    ga('create',' UA-10020436-28','auto');ga('send','pageview');
  </script>
</html>

app/views/tracks/_form.html.erb
<%= form_for(@track) do |f| %>
  <% if @track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% @track.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tracks/_top_tracks.html.erb
<% if @soundcloud_playlist %>
  <%
      meta title: "#{@soundcloud_playlist.title} on Console.fm",
      description: @soundcloud_playlist.description,
      twitter: {
        card: "summary",
        site: "@consolefm"
      }
  %>
<% end %>

<div id="js-track-height" class="container clearfix">
  <div plangular="<%= @playlist_url || "http://soundcloud.com/alexbaldwin/likes" %>">
    <div class="sm-col sm-col-12 md-col-6">
      <ul ng-if="tracks" class="tracks list-reset mt2">
        <li ng-repeat="track in tracks | limitTo:100" class="track" ng-class="{'is-active': player.playing === track.src }">
          <div
            class="flex flex-center full-width left-align"
            title="Play {{track.title }}"
            ng-click="playPause($index)">
            <div class="track-art flex-none" alt="{{ track.title }}" style="background: url({{ track.artwork_url.replace('large','t300x300') }})">
              <div class="overlay flex flex-center">
                <span class="plus mx-auto block">
                  <img class="icon white" src="/assets/player.svg">
                </span>
              </div>
            </div>
            <div class="flex-auto"> 
              <h2 class="track-title">{{track.title}}</h2>
              <h3 class="track-artist">{{track.user.username}}</h3>
            </div>
          </div>
        </li>
      </ul>
    </div>
    <div class="kimono z2"></div>
    <div id="js-affix-player" class="z3 playing-view md-show col col-6" style="position: fixed;">
      <div ng-if="track" class="center playing-player p1 mt2">
        <img ng-src="{{ track.artwork_url.replace('large','t500x500') }}" alt="{{ track.title }}"
        height="360" width="360" class="playing-art" />
        <h2 class="playing-title truncate">{{track.title}}</h2>
        <h3 class="playing-artist truncate">{{track.user.username}}</h3>
        <div class="flex flex-center py2">
          <div class="flex-grow"></div>
          <button class="flex-none"
            title="Play Previous Track"
            hotkey="{left: previous}"
            ng-click="previous()">
            <img class="icon" src="/assets/previous.svg">
          </button>
          <div class="flex-none radial-progress" ng-value="(currentTime / duration) * 100 | number:0  || 0">
            <div class="circle">
              <div class="mask full">
                <div class="fill"></div>
              </div>
              <div class="mask half">
                <div class="fill"></div>
                <div class="fill fix"></div>
              </div>
            </div>
            <div class="inset">
              <div class="percentage">
                <button class="playing-play"
                  title="Play/Pause"
                  ng-click="playPause(index)">
                  <img ng-if="player.playing !== track.src" class="icon" src="/assets/play.svg">
                  <img ng-if="player.playing === track.src" class="icon" src="/assets/pause.svg">
                </button>
              </div>
            </div>
          </div>
          <button class="flex-none"
            title="Play Next Track"
            hotkey="{right: next}"
            ng-click="next()">
            <img class="icon" src="/assets/next.svg">
          </button>
          <div class="flex-grow"></div>
        </div>
        <aside ng-hide="true" class="mt4">
          <a href="" class="mr2">Share</a>
          <a ng-href="{{track.permalink_url}}">View on SoundCloud</a>
        </aside>
      </div>
    </div>

  </div>
</div>

app/views/tracks/edit.html.erb
<h1>Editing Track</h1>

<%= render 'form' %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<%= render 'top_tracks' %>

app/views/tracks/new.html.erb
<h1>New Track</h1>

<%= render 'form' %>

<%= link_to 'Back', tracks_path %>

app/views/tracks/playlist.html.erb
<%= render 'top_tracks' %>

app/views/tracks/show.html.erb
<%
    meta title: "#{@soundcloud_track.title} - #{@soundcloud_track.user.username} on Console.fm",
    description: @soundcloud_track.description,
    twitter: {
      card: "summary",
      site: "@consolefm"
    },
    og: {
      image: @soundcloud_track.artwork_url
    }
%>

<div class="clearfix">
<div plangular="<%= @url %>" class="mb4 relative" style="min-height: 50vh; background-repeat: no-repeat; background-size: cover; background-position: center center; background-image: url({{ track.artwork_url.replace('large','t500x500') }})">
    <div class="playing-player px-1 bg-darken-4 absolute full-width flex flex-center" style="height: 100%">
      <div class="flex-auto center">
      <h2 class="playing-title truncate white">{{track.title}}</h2>
      <h3 class="playing-artist truncate white">{{track.user.username}}</h3>
      <div class="flex flex-center">
        <div class="flex-grow"></div>
        <button class="flex-none playing-play"
          title="Play/Pause"
          ng-click="playPause(index)">
          <img ng-if="player.playing !== track.src" class="icon" src="/assets/play.svg">
          <img ng-if="player.playing === track.src" class="icon" src="/assets/pause.svg">
        </button>
        <div class="flex-grow"></div>
      </div>
    </div>
  </div>
  </div>
</div>

<%= render 'top_tracks' %>

<script>
  $('#js-affix-player').affix({
  offset: {
    top: function () {
      return (screen.height / 2)
    }
  }
  })
</script>